name: Flatpak build of OpenSceneGraph
on: [push]
jobs:
  flatpak-build:
    runs-on: ubuntu-latest
    container:
      image: freedesktopsdk/sdk:22.08
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      # a build is successful if this finishes without error
      # the intent is not to produce a binary
      - name: Create the makefiles with Ninja
        run: cmake -B build -G Ninja
      - name: Build OSG
        run: cd build/ && ninja
